psk/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [path('about/', views.About.as_view(), name='about')]

psk/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/<str:type>/', views.company, name='company'),
    path('products/<str:type>/<str:company>/', views.model, name='models'),
    path(
        'products/<str:type>/<str:company>/<slug:slug>/',
        views.Products,
        name='products',
    ),
]

psk/psk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('products.urls', namespace='products')),
    path("admin/", admin.site.urls),
    path('', include('about.urls', namespace='about')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psk/products/models.py
from django.db import models


class Type(models.Model):
    type_name = models.CharField('Название типа', max_length=50)
    type_name_russian = models.CharField(
        'Название типа на русском', max_length=50
    )

    class Meta:
        verbose_name = 'Типы оборудования'

    def __str__(self) -> str:
        return self.type_name_russian


class Company(models.Model):
    company_name = models.SlugField('Имя компании', max_length=200)
    available_types = models.ManyToManyField(
        Type, related_name='companys', verbose_name='Доступные типы'
    )

    class Meta:
        verbose_name = 'Компании'

    def __str__(self) -> str:
        return self.company_name


class Modl(models.Model):
    model_name = models.CharField('Имя модели', max_length=500)
    model_type = models.ForeignKey(
        Type,
        on_delete=models.CASCADE,
        verbose_name='Тип модели',
        related_name='models',
    )
    company_name = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        verbose_name='Компания',
        related_name='models',
    )
    model_slug = models.SlugField(
        'Ссылка на модель',
        blank=True,
        unique=True,
        help_text='Ссылка, по которой будут доступны расходники к модели (можно оставить пустым)',
    )
    show_in_psk = models.BooleanField(
        'Показать на сайте plazmapsk',
        default=False,
        help_text='Настройка отображения на сайте',
    )

    class Meta:
        verbose_name = 'Модели'

    def __str__(self) -> str:
        return self.model_name

    def save(self, *args, **kwargs):
        if not self.model_slug:
            for char in self.model_name:
                if char == ' ':
                    char = '_'
                self.model_slug += char
        super().save(*args, **kwargs)


class Product(models.Model):
    article = models.CharField('Артикул', max_length=15)
    name = models.CharField('Имя продукта', max_length=200)
    description = models.TextField(
        'Описание',
    )
    modl = models.ForeignKey(
        Modl,
        on_delete=models.CASCADE,
        verbose_name='Модель оборудования',
        related_name='products',
    )
    img = models.ImageField(
        'Изображение',
        upload_to='products/',
        null=True,
        help_text='Изображение расходника',
    )

    class Meta:
        verbose_name = 'Продукты'

    def __str__(self) -> str:
        return self.name

psk/about/views.py
from django.views.generic.base import TemplateView


class About(TemplateView):
    template_name = 'about/about.html'

psk/products/views.py
from django.shortcuts import get_object_or_404, render

from .models import Company, Modl, Product, Type


def index(request):
    return render(request, 'products/index.html')


def Products(request, type, company, slug):
    modl = get_object_or_404(Modl, model_slug=slug)
    products = modl.products.all()

    context = {
        'model': modl,
        'products': products,
    }

    return render(request, 'products/products.html', context)


def model(request, type, company):
    company = Company.objects.get(company_name=company)
    types = Type.objects.get(type_name=type)
    tp = ''
    if type == 'lazer':
        tp = 'лазерного'
    elif type == 'plazma':
        tp = 'плазменного'
    elif type == 'welding':
        tp == 'сварочного'

    context = {
        'tp': tp,
        'type': types,
        'company': company,
        'models': Modl.objects.filter(model_type=types).filter(
            company_name=company
        ),
    }

    return render(request, 'products/models.html', context)


def company(request, type):
    input_type = Type.objects.get(type_name=type)
    context = {
        'type': input_type,
        'companys': input_type.companys.all(),
    }
    return render(request, 'products/company.html', context)

psk/templates/about/about.html
{% extends "base.html" %}

{% block title %}
Наши контакты
{% endblock title %}

<div class = "container">
    
</div>


{% block content %}
<div class = "container">
    <div class = "row">
        <p class = "text-center"><b>Наши контакты:</b></p>
    </div>
    <div class = "row">
        <div class = "col-6"><p>Организационно-правовая форма и фирменное наименование:</p></div>
        <div class = "col-6 text-end"><p>Общество с Ограниченной  Ответственностью  «ПлазмаСнабКомплект» (ООО «ПлазмаСнабКомплект»)</p></div>
        <div class = "col-6"><p>Юридический адрес:</p></div>
        <div class = "col-6 text-end"><p>220089, г. Минск, ул. Гурского 37, офис 5Н, комната №18/11</p></div>
        <div class = "col-6"><p>Фактическое местонахождение:</p></div>
        <div class = "col-6 text-end"><p>220131, Минск, ул. Гамарника, д30, офис 353</p></div>
        <div class = "col-6"><p>Телефон/факс Участника (с указанием кода города):</p></div>
        <div class = "col-6 text-end"><p><a href = "tel:+375296566194">8 (029) 656 61 94</a>, <a href = "tel:+375173221264"> 8 (017) 322 12 64</a>, <a href = "tel:+375173221265">8 (017) 322 12 65</a></p></div>
        <div class = "col-6"><p>Адрес электронной почты:</p></div>
        <div class = "col-6 text-end"><p><a href = "mailto:plazmapsk@gmail.com">plazmapsk@gmail.com</a></p></div>
    </div>

    <hr class="featurette-divider">
    
<p class = "text-center"><b>Мы на карте</b></p>


<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A0b0446832a69380e719dd382bb09e7227dbc0e28bb6983d5e2077aa5c05fbb4c&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
<hr class="featurette-divider">
</div>
{% endblock content %}

psk/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    {% include "includes/connections.html" %}
    <title>{% block title %}{% endblock title %}</title>
  </head>


  <body>
    
<header>
    {% include "includes/header.html" %}
</header>

<main>

  {% include "includes/carousel.html" %}


  {% block content %}{% endblock content %}

  <footer class="container">
    {% include "includes/footer.html" %}
  </footer>
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

      
  </body>
</html>

psk/templates/includes/carousel.html
 {% load static %}

 <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src = "{% static "img/slide-4.jpg" %}" class = "img-fluid"></img>
            <img src = "{% static "img/bg-content.jpg" %}" class = "img-fluid transparent50"></img>
            <div class="container">
              <div class="carousel-caption">
                <h1>Плазма</h1>
                <p>Плазменная резка – один из наиболее эффективных методов термического раскроя металла. Аппараты для плазменной резки являются высокотехнологичными машинами. Не последнюю роль в качестве и комфорте их эксплуатации играют расходные части. Являясь официальным дилером крупнейшего мирового производителя плазменного оборудования и расходных частей к нему компании HYPERTHERM и ее дочерней компании Centricut, мы имеем возможность поставлять плазменные комплектующие высочайшего качества. Вот неполный перечень резаков различных производителей, комплектуемых данными расходными частями.</p>
                <p><a class="btn btn-lg btn-primary" href="{% url "products:company" "plazma" %}">Подробнее</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src = "{% static "img/slide-2.jpg" %}" class = "img-fluid"></img>
            <img src = "{% static "img/bg-content.jpg" %}" class = "img-fluid transparent50"></img>
            <div class="container">
              <div class="carousel-caption">
                <h1>Лазер</h1>
                <p>Компания «ПлазмаСнабКомплект» занимается поставкой расходных материалов для оборудования лазерной резки.
                  Расходные материалы, приобретаемые в нашей компании обеспечивают отличные характеристики резки при самых низких затратах. Приобретаемые расходные детали обладают хорошей точностью и неизменностью характеристик при каждом заказе.</p>
                <p><a class="btn btn-lg btn-primary" href="{% url "products:company" "lazer" %}">Подробнее</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src = "{% static "img/slide-3.jpg" %}" class = "img-fluid"></img>
            <img src = "{% static "img/bg-content.jpg" %}" class = "img-fluid transparent50"></img>
            <div class="container">
              <div class="carousel-caption">
                <h1>Сварка</h1>
                <p>Компания «ПлазмаСнабКомплект» имеет возможность поставлять расходные материалы для сварочного оборудования.
                  Сварочные расходные детали, приобретаемые у нашей компании отличаются качественным исполнением и не высокими ценами.</p>
                <p><a class="btn btn-lg btn-primary" href="{% url "products:company" "welding" %}">Подробнее</a></p>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Следующий</span>
        </button>
      </div>

psk/templates/includes/connections.html
{% load static %}

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="{% static "css/carousel.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">

psk/templates/includes/footer.html
<p class="float-end"><a href="#">Вверх</a></p>
<div class = "container">
<p> Контакты: </p>
<p> Адрес: 220131 г. Минск ул Гамарника, д 30(БЦ "зеленый луг") офис 353</p>

<p> Телефоны: <a href = "tel:+375296566194">8 (029) 656 61 94</a>, <a href = "tel:+375173221264"> 8 (017) 322 12 64</a>, <a href = "tel:+375173221265">8 (017) 322 12 65</a></p>
<p>Email: <a href = "mailto:plazmapsk@gmail.com">plazmapsk@gmail.com</a></p>
<p class = "text-center"><b>&copy; {{ year }} ООО "ПлазмаСнабКомплект"</b></p>
</div>

psk/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        ООО "ПлазмаСнабКомплект"
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
          </li>
          {% for type in all_types %}
          {% if type.companys.all %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ type.type_name_russian }}</a>
            <ul class="dropdown-menu">
                {% for company in type.companys.all %}
              <li><a class="dropdown-item" href="{% url "products:models" type.type_name company.company_name %}">{{ company.company_name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% endif %}
         {% endfor %}
          <li class="nav-item">
            <a class="nav-link" href = "{% url "about:about" %}">Контакты</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Поиск</button>
        </form>
      </div>
    </div>
  </nav>

psk/templates/products/company.html
{% extends "base.html" %}

{% block title %}
{% if type.type_name == "plazma" %}
Плазма
{% elif type.type_name == "lazer" %}
Лазер
{% elif type.type_name == "welding" %}
Сварка
{% endif %}
{% endblock title %}


{% block content %}
<div class = "container marketing">
    <div class = "row text-center">
      {% if type.type_name == "plazma" %}
<p><h2>Плазма</h2></p>
{% elif type.type_name == "lazer" %}
<p><h2>Лазер</h2></p>
{% elif type.type_name == "welding" %}
<p><h2>Сварка</h2></p>
{% endif %}
    </div>
<div class="row">
    {% for company in companys %}
    <div class="col-lg-4">
      <a href = "{% url "products:models" type.type_name company.company_name %}" class = "btn btn-outline-primary"><h2 class="fw-normal">{{ company.company_name }}</h2></a>
    </div>
    {% endfor %}

    <hr class="featurette-divider">
  </div>
</div>

{% endblock content %}

psk/templates/products/index.html
{% extends 'base.html' %}

{% block title %}ООО "ПлазмаСнабКомплект"{% endblock title %}

{% block content %}


  <div class="container marketing">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

  </div>

  {% endblock content %}

psk/templates/products/models.html
{% extends "base.html" %}

{% block title %}
{% if type.type_name == "plazma" %}
Плазма
{% elif type.type_name == "lazer" %}
Лазер
{% elif type.type_name == "welding" %}
Сварка
{% endif %}
{% endblock title %}


{% block content %}
<div class = "container marketing">
    <div class = "row text-center text-danger">
        <p><h1>Мы готовы предложить вам расходные детали для {{ tp }} оборудования {{ company }}:</h1></p>
    </div>
<div class="row">
    {% for model in models %}
    <div class="col-lg-4">
      <h3 class="fw-normal">{{ model.model_name }}</h3>
      <p>Описание</p>
      <p><a class="btn btn-secondary" href="{% url "products:products" type.type_name company model.model_slug %}">Продукция »</a></p>
    </div>
    {% endfor %}

    <hr class="featurette-divider">
  </div>
</div>

{% endblock content %}

psk/templates/products/products.html
{% extends "base.html" %}

{% block title %}
{{ model.model_name }}
{% endblock title %}


{% block content %}
<div class = "container marketing">
    <div class = "row text-center text-danger">
        <p><h2>Расходные детали для оборудования {{ model.model_name }}</h2></p>
    </div>
</div>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for product in products %}
      <div class="col">
        <div class="card shadow-sm"> 
          <img src = "{{ product.img.url }}" class = "card-img-top img-fluid"></img>
          <div class="card-body">
            <p class = "card-text text-center"><b>{{ product.name }}</b></p>
            <p class="card-text">{{ product.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">Артикул: {{ product.article }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}


    </div>
  </div>
</div>

{% endblock content %}